name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myapp/requirements.txt

    - name: Run tests 
      env:
        DJANGO_SETTINGS_MODULE: myapp.settings.developpement
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd myapp
        pytest --cov=myapp2 --cov-report=term --cov-fail-under=80